### ISSUE TITLE
Using with Swift package manager

### ISSUE THREAD

**Issue by mantas** [AndrewBarba/Bluebird.swift#3]
I tried to import Bluebird into command line app using Swift package manager. It wouldn't compile and was giving following error:

```
error: use of undeclared type 'DispatchQueue'
```

I had to add "import Foundation" to all Bluebird's files to make it compile. Is there any reason why it was omitted? Did I miss some configuration? Meanwhile Alamofire compiled right away..

**Comment by AndrewBarba** [comment]
Hey thanks for bringing this up, I am going to push a fix right now. I guess on Carthage / CocoaPods they use the header file [here](https://github.com/AndrewBarba/Bluebird.swift/blob/master/Source/Bluebird.h) which imports Foundation automatically to all swift files. Hang tight and will have a fix soon

**Comment by mantas** [comment]
No problem, I got it working for now. Thanks for a quick reply.

**Comment by AndrewBarba** [comment]
Here you go: https://github.com/AndrewBarba/Bluebird.swift/releases/tag/2.0.1
