### ISSUE TITLE
Q: How to create a pending Promise?

### ISSUE THREAD

**Issue by lastcc** [AndrewBarba/Bluebird.swift#4]
RT.

I'm writing code to wrap the delegation pattern to Promise.

Can I create a pending promise?

I'm new to Promise/Future Programming, and I find it is not obvious to create a pending promise with Bluebird.swift.

Some other problems:
How to get value 1 & value 2 in the 3rd `then closure?

**Comment by AndrewBarba** [comment]
For a pending Promise use [Promise.defer](https://andrewbarba.github.io/Bluebird.swift/Classes/Promise.html#/s:8Bluebird7PromiseC5deferACyxG7promise_yxc7resolveys5Error_pc6rejecttyFZ)

Here's a quick example:

```swift
class ProfileController: FavoritesDelegate {
    
    private var favoritesResolver: Promise<[Favorite]>.Resolver?  

    func selectFavorites() -> Promise<[Favorite]> {
        let resolver = Promise<[Favorite]>.defer()
        self.favoritesResolver = resolver
        presentSelectFavoritesController(delegate: self)
        return resolver.promise
    }

    func favoritesController(_ controller: FavoritesController, selected favorites: [Favorite]) {
        self.favoritesResolver?.resolve(favorites)
    }
}
```

**Comment by AndrewBarba** [comment]
Feel free to open an issue for the other questions, I don't fully understand it here. Also check out the documentation: https://andrewbarba.github.io/Bluebird.swift/index.html

**Comment by lastcc** [comment]
Hi thank you for your reply.  i have successfully transformed my code.

This lib deserves more stars. I have looked into promisekit, and its wraping of CLLocation Api is buggy.

**Comment by AndrewBarba** [comment]
That's awesome! Thanks so much for the compliment

**Comment by lastcc** [comment]
Hi @AndrewBarba I'm sorry to bother you ... given the following code I have 3 problems:

1. Is there an elegant way to retry? Do I have to wrap retry logic some where else, off the chain?
2. Is there a way to jump to `addDatabaseSubscriptionPromise` in the catch block if I hit `databaseSubscriptionError`?
3. Could I handle error in place? Is this a correct pattern, or anti-pattern? :
`Bluebird.try { self.accountStatusPromise().catch { ... } }.then {.....}`

https://github.com/lastcc/scripts/blob/c0b1dc75c1b77b6686978b19d2fe4e46e0c075e2/temp.swift#L249-L280

**Comment by lastcc** [comment]
```swift
    public func cloudKitSetup() {
        
        Bluebird.try {
            self.accountStatusPromise()
        }.then { _ in
            self.addDatabaseSubscriptionPromise(for: self.privateCloudDatabase, subscriptionID: "private-changes")
        }.then { _ in
            self.fetchDatabaseChangesPromise(self.privateCloudDatabase).recover({ (error) -> Promise<[CKRecordZoneID]> in
                if let ckError = error as? CKError, ckError.code == CKError.changeTokenExpired {
                    return self.fetchDatabaseChangesPromise(self.privateCloudDatabase)
                } else {
                    throw error
                }
            })
        }.then { changedRecordZoneIDs in
            self.fetchZoneChangesPromise(changed: changedRecordZoneIDs, from: self.privateCloudDatabase)
        }.then { changedRocords, deletedRecordIDs in
            // update UI
        }.catch { error in
            // FIXME: unhandled error
            if let kirinoError = error as? KirinoCloudError {
                switch kirinoError {
                case .accountNotAvailable:
                    print("accountNotAvailable")
                case .databaseSubscriptionError(let infoDict): break
                case .someZoneTokenExpired(let expiredRecordZoneIDs): break
                }
            } else {
                print(error)
            }
        }
    }
```

**Comment by lastcc** [comment]
docs:
the docs does not include `defer` keyword

spelling error: `givin`
timeout: thrown if a Promise does not resolve in the givin number of seconds
https://andrewbarba.github.io/Bluebird.swift/Enums/BluebirdError.html

**Comment by AndrewBarba** [comment]
@lastcc I just added cancellation support: https://github.com/AndrewBarba/Bluebird.swift/releases/tag/2.3.0

This is a first step towards retry logic which I am working on next
