### ISSUE TITLE
Promise<Void>.resolve()

### ISSUE THREAD

**Issue by Oleygen** [AndrewBarba/Bluebird.swift#5]
Hi there! At first I'd like to say that you did a great job creating this promise framework! 
I'm thinking on migrating from closure-style async API to promise-style, and I need your help here.

Sometimes needed to not pass any argument in a resolve block of promise, this is where Promise<Void> appears. Whenever I call resolve() on such promise, it requires an arguments, which doesn't make sense. 
What I'm asking for is: can you please add a function with signature without any parameter for void-parametrized promise? Thanks in advance. 

Related image: https://imgur.com/fGtH99j

**Comment by AndrewBarba** [comment]
@Oleygen I've run into this as well, and it seems to be how Swift handles Void with generic types. I will research this more, but for now I think you can just call `resolve(())` using an empty tuple as the argument.
